### ISSUE TITLE
Warning: Calling 'depends_on ... => :run' is deprecated!

### ISSUE THREAD

**Issue by zerda** [datawire/homebrew-blackbird#5]
I was upgrading telepresence to v0.81, and got this warning:
```
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:10:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:11:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!
```

HOMEBREW_VERSION: 1.5.14-43-g65651b3

**Comment by ark3** [comment]
This will be fixed in the next release.
