### ISSUE TITLE
Can't install on macOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by w18enson** [datawire/homebrew-blackbird#6]
Can you help on this?

Full log :

```
brew install socat datawire/blackbird/telepresence                                                                                                                                                                                               

Updating Homebrew...
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:10:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:11:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!

Error: socat 1.7.3.2_1 is already installed
To upgrade to 1.7.3.2_2, run `brew upgrade socat`
==> Installing telepresence from datawire/blackbird
Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:10:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!

Warning: Calling 'depends_on ... => :run' is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/datawire/homebrew-blackbird/Formula/telepresence.rb:11:in `<class:Telepresence>'
Please report this to the datawire/blackbird tap!

==> Downloading https://github.com/datawire/telepresence/archive/0.81.tar.gz
Already downloaded: /Users/w18enson/Library/Caches/Homebrew/telepresence-0.81.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
Already downloaded: /Users/w18enson/Library/Caches/Homebrew/telepresence--homebrew-virtualenv-15.2.0.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/telepresence--homebrew-virtualenv-20180410-28923-1xcgzqq/target --single-version-externally-managed --record=installed.txt
==> python3 -s /tmp/telepresence--homebrew-virtualenv-20180410-28923-1xcgzqq/target/bin/virtualenv -p python3 /usr/local/Cellar/telepresence/0.81/libexec
==> /usr/local/Cellar/telepresence/0.81/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed git+https://github.com/datawire/sshuttle.git@telepresence
Last 15 lines from /Users/w18enson/Library/Logs/Homebrew/telepresence/03.pip:
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/Cellar/telepresence/0.81/libexec/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
pip._vendor.requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /pypi/pip/json (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x10bf97f28>: Failed to establish a new connection: [Errno 61] Connection refused',))

```

**Comment by ark3** [comment]
I'm not able to reproduce the `ConnectionError` crash. Is this still happening for you?

**Comment by w18enson** [comment]
this is still happening to me after a few try (another internet source and enable / disable vpn)

**Comment by w18enson** [comment]
suddenly, I can install it today
full log 
```
brew install socat datawire/blackbird/telepresence        

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, caskroom/cask).
==> New Formulae
gitlab-gem
==> Updated Formulae
kubernetes-cli ✔      emscripten            libsoxr               qd
yarn ✔                fig2dev               links                 qtfaststart
abcmidi               flow                  log4cplus             rancher-cli
abyss                 futhark               monero                recoverjpeg
amqp-cpp              gegl                  mutt                  remctl
apibuilder-cli        globus-toolkit        mypy                  silk
asio                  go-jira               nanopb-generator      softhsm
aspectj               grpc                  nginx                 sparse
babeld                imlib2                nvm                   sqliteodbc
bibtex2html           influxdb              packmol               src
chronograf            jansson               pam_yubico            subversion
clojure               jenkins               perl@5.18             testssl
consul                keychain              phplint               timelimit
discount              launch                phpunit               tmux
dmd                   lcdf-typetools        pioneers              tup
dnscrypt-proxy        libgpg-error          poco                  xonsh
dnsdist               libhttpseverywhere    proguard              yle-dl
docker2aci            liblwgeom             py2cairo              youtube-dl
dub                   librealsense          py3cairo              znapzend

Warning: socat 1.7.3.2_2 is already installed and up-to-date
To reinstall 1.7.3.2_2, run `brew reinstall socat`
==> Installing telepresence from datawire/blackbird
==> Installing dependencies for datawire/blackbird/telepresence: sqlite
==> Installing datawire/blackbird/telepresence dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.23.1.high_sierra.bottle.tar
######################################################################## 100.0%
==> Pouring sqlite-3.23.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/sqlite/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/sqlite/3.23.1: 11 files, 3MB
==> Installing datawire/blackbird/telepresence
==> Downloading https://github.com/datawire/telepresence/archive/0.82.tar.gz
==> Downloading from https://codeload.github.com/datawire/telepresence/tar.gz/0.82
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec00
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/telepresence--hom
==> python3 -s /tmp/telepresence--homebrew-virtualenv-20180416-20779-dmp9ia/target/bin/vi
==> /usr/local/Cellar/telepresence/0.82/libexec/bin/pip install -v --no-deps --no-binary
==> /usr/local/Cellar/telepresence/0.82/libexec/bin/pip install -v --no-deps --no-binary
==> Caveats
Use of the container method requires socat.
  brew install socat
==> Summary
🍺  /usr/local/Cellar/telepresence/0.82: 1,007 files, 10.8MB, built in 38 seconds
```

Thankyou @ark3 for your time checking this
